# Generated by Django 3.1.7 on 2021-04-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(verbose_name='Explanation')),
                ('parents', models.ManyToManyField(related_name='children', to='terminology.Term')),
            ],
        ),
    ]
