# Generated by Django 3.1.7 on 2021-04-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0002_term_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=512, unique=True, verbose_name='Name'),
        ),
    ]
